# -*- coding: utf-8 -*-
"""summarizer.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hqMhcxXcWIpMaM9x7h-539uswVvv7PD9
"""

pip install nltk

import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize, sent_tokenize
from heapq import nlargest

# Download nltk resources if not already downloaded
nltk.download('punkt')
nltk.download('stopwords')

def text_summarizer(text, num_sentences=3):
    # Tokenize the text into sentences
    sentences = sent_tokenize(text)

    # Tokenize the text into words
    words = word_tokenize(text)

    # Remove stopwords
    stop_words = set(stopwords.words('english'))
    words = [word for word in words if word.lower() not in stop_words]

    # Calculate word frequencies
    word_freq = {}
    for word in words:
        if word in word_freq:
            word_freq[word] += 1
        else:
            word_freq[word] = 1

    # Calculate sentence scores based on word frequencies
    sentence_scores = {}
    for sentence in sentences:
        for word in word_tokenize(sentence.lower()):
            if word in word_freq:
                if sentence not in sentence_scores:
                    sentence_scores[sentence] = word_freq[word]
                else:
                    sentence_scores[sentence] += word_freq[word]

    # Select the top 'num_sentences' sentences with highest scores
    summary_sentences = nlargest(num_sentences, sentence_scores, key=sentence_scores.get)
    summary = ' '.join(summary_sentences)

    return summary

# Main function
def main():
    # Input text from the user
    text = input("Enter the text you want to summarize:\n")

    # Set the number of sentences in the summary
    num_sentences = int(input("Enter the number of sentences for the summary (default is 3): ") or 3)

    # Generate summary
    summary = text_summarizer(text, num_sentences)
    print("\nSummary:")
    print(summary)

if __name__ == "__main__":
    main()